import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { getImages } from "../lib/get-images";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// This function runs only on the server side
export async function getStaticProps() {
    const images = await getImages(2);

    // Props returned will be passed to the page component
    return { props: { images } };
}

export default function Home({ images }: Props) {
    return (
        <>
            <Head>
                <title>AI-lbum</title>
                <meta name="description" content="An AI art gallery" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <h1 className={inter.className}>AI-lbum</h1>
                </div>
                <div className={styles.grid}>
                    {
                        // map over the images and render them

                        images.map((image: Image) => (
                            <div key={image._id} className={styles.card}>
                                <Image
                                    src={image.imageUrl}
                                    alt="A random image"
                                    width={512}
                                    height={512}
                                    priority
                                />
                            </div>
                        ))
                    }
                </div>

                <div className={styles.grid}>
                    <Link href="/new-image" className={styles.card}>
                        <h2 className={inter.className}>
                            Generate <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Generate a new image from a prompt.
                        </p>
                    </Link>

                    <Link href="/gallery" className={styles.card}>
                        <h2 className={inter.className}>
                            Gallery <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            View a gallery of images generated by the AI.
                        </p>
                    </Link>
                </div>
            </main>
        </>
    );
}

interface Image {
    _id: string;
    imageUrl: string;
}

interface Props {
    images: Array<Image>;
}
